#!/bin/bash
set -e

./gradlew clean compileJava assemble build

function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

eval $(parse_yaml sam-template.yaml)

LAYER_PACKAGE=build/distributions/serverless-java-spring-boot-layer1.zip
LAYER_NAME=`basename $LAYER_PACKAGE`

aws s3 cp $LAYER_PACKAGE s3://${S3_BUCKET}/$LAYER_NAME
aws lambda publish-layer-version --layer-name serverless-java-spring-boot-layer1 \
    --content S3Bucket=${S3_BUCKET},S3Key=${LAYER_NAME} \
    --compatible-runtimes java8


LAYER_ARN=`aws lambda list-layer-versions --layer-name serverless-java-spring-boot-layer1 --max-items 1 | jq ".LayerVersions[0].LayerVersionArn" -r`
echo "JAR layer ARN: ${LAYER_ARN}"

aws cloudformation package --template-file sam-template.yaml --s3-bucket ${S3_BUCKET} --s3-prefix java --output-template-file sam-package.yaml

PARAMS="SNSTopic=${SNS_TOPIC} SQSQueue=${SQS_QUEUE} CodeLayers=${LAYER_ARN}"

aws cloudformation deploy --template-file sam-package.yaml --stack-name ServerlessSpringApi --parameter-overrides ${PARAMS} --capabilities CAPABILITY_IAM

aws cloudformation describe-stacks --stack-name ServerlessSpringApi

