AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Parameters:
  Stage:
    Type: String
    Default: dev

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: Stage
      Variables:
        Stage:
          Ref: Stage
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: my.service.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: "build/distributions/serverless-java-spring-boot.zip"
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment: 
        Variables:
          # Specify here variables for deployment,
          # override local using sam-local-env.json
          SPRING_PROFILES_ACTIVE: aws
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: 
              Ref: ApiGatewayApi
            Path: /ping
            Method: GET
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
