version: 2

jobs:
  # Build and run tests
  build:
    working_directory: ~/serverless
    docker:
      # https://discuss.circleci.com/t/spring-boot-application-build-failed-due-to-test-failure/27687
      - image: circleci/openjdk:8u171-jdk-node-browsers
    steps:
      - checkout
      - run: python --version
      - run: pip install --user awscli
      - run: pip install --user aws-sam-cli
      - run: ./gradlew build
      - save_cache:
          key: docs-{{ checksum "build.gradle" }}
          paths:
            - ~/.m2
      - store_artifacts:
          path: ~/serverless/build/reports
      - store_artifacts:
          path: ~/serverless/build/test-results
      - run: 
          when: on_fail
          command: find > ~/serverless/all-files.txt
      - store_artifacts:
          path: ~/serverless/all-files.txt
workflows:
  version: 2
  build:
    jobs:
      - build